// Bundle src/*.ts → extension/*.js using Bun, then copy static assets.
// Each entry (content-script, sidepanel, background, lucide) becomes a
// single self-contained .js file — content scripts don't load ES modules,
// so bundling is mandatory.

import {mkdirSync, copyFileSync, writeFileSync, readFileSync, existsSync, rmSync, readdirSync} from 'node:fs';
import {resolve, basename} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = resolve(fileURLToPath(import.meta.url), '..', '..');
const srcDir = resolve(root, 'src');
const distDir = resolve(root, 'extension');

mkdirSync(distDir, {recursive: true});

// ─── Copy DESIGN.md / SKILL.md templates as extension resources ────────────
// Earlier versions baked these into the sidepanel.js IIFE as string
// constants — that pushed the bundle to ~1.95MB because the files are
// 184KB + 178KB respectively. Better architecture: ship them as separate
// .md files inside the extension and load on demand. The sidepanel
// fetches them via `chrome.runtime.getURL('templates/...')` only when
// the user actually opens the editor modal or exports an archive.
//
// Per-user override: if `src/templates/local.DESIGN.md` exists, its
// content gets copied as `extension/templates/local.DESIGN.md`. The
// sidepanel prefers `local.*` over the generic template on first
// install so a developer can fork the extension and ship a build
// pre-loaded with their actual design source-of-truth. Gitignored.
//
// Only a small `templates.gen.ts` module is emitted — just lists which
// resources are present (so the sidepanel knows which file to fetch
// without a probe round-trip).
{
  const srcTemplatesDir = resolve(srcDir, 'templates');
  const distTemplatesDir = resolve(distDir, 'templates');
  mkdirSync(distTemplatesDir, {recursive: true});
  type TplCopy = {srcName: string; distName: string; required: boolean; key: 'designTemplate' | 'skillTemplate' | 'localDesign' | 'localSkill'};
  const copies: TplCopy[] = [
    {srcName: 'DESIGN.template.md', distName: 'DESIGN.template.md', required: true, key: 'designTemplate'},
    {srcName: 'PinchGrab.SKILL.template.md', distName: 'PinchGrab.SKILL.template.md', required: true, key: 'skillTemplate'},
    {srcName: 'local.DESIGN.md', distName: 'local.DESIGN.md', required: false, key: 'localDesign'},
    {srcName: 'local.SKILL.md', distName: 'local.SKILL.md', required: false, key: 'localSkill'},
  ];
  const present: Record<TplCopy['key'], boolean> = {designTemplate: false, skillTemplate: false, localDesign: false, localSkill: false};
  for (const c of copies) {
    const src = resolve(srcTemplatesDir, c.srcName);
    if (!existsSync(src)) {
      if (c.required) {
        console.error(`Required template missing: ${src}`);
        process.exit(1);
      }
      continue;
    }
    copyFileSync(src, resolve(distTemplatesDir, c.distName));
    present[c.key] = true;
  }
  const gen = `// Auto-generated by scripts/build-extension.ts — do not edit.
// Tells the sidepanel which template resources exist in this build.
// Actual content lives as .md files under extension/templates/, loaded
// lazily via chrome.runtime.getURL — see loadTemplate() in sidepanel.ts.
export const TEMPLATES_PRESENT = ${JSON.stringify(present)} as const;
`;
  writeFileSync(resolve(srcDir, 'templates.gen.ts'), gen);
  console.log(`Templates copied to extension/templates/ (local DESIGN: ${present.localDesign ? 'yes' : 'no'}, local SKILL: ${present.localSkill ? 'yes' : 'no'})`);
}

// ─── TS entries ───────────────────────────────────────────────────────────
type Entry = {input: string; output: string; minify?: boolean};
const ENTRIES: Entry[] = [
  // lucide.ts is imported by sidepanel.ts and bundled in — no standalone build.
  {input: 'content-script.ts', output: 'content-script.js'},
  {input: 'sidepanel.ts', output: 'sidepanel.js'},
  {input: 'background.ts', output: 'background.js'},
];

const minify = process.env.NODE_ENV === 'production' || process.argv.includes('--minify');

for (const entry of ENTRIES) {
  const result = await Bun.build({
    entrypoints: [resolve(srcDir, entry.input)],
    target: 'browser',
    format: 'iife',
    minify,
    sourcemap: minify ? 'none' : 'inline',
  });
  if (!result.success) {
    console.error(`Build failed for ${entry.input}:`);
    for (const log of result.logs) console.error(log);
    process.exit(1);
  }
  const out = await result.outputs[0]!.text();
  const dest = resolve(distDir, entry.output);
  writeFileSync(dest, out);
  const sizeKb = (out.length / 1024).toFixed(1);
  console.log(`Wrote ${dest} (${sizeKb} KB${minify ? ', minified' : ''})`);
}

// ─── Static assets ────────────────────────────────────────────────────────
const PASSTHROUGH = ['manifest.json', 'sidepanel.html', 'sidepanel.css'];
for (const f of PASSTHROUGH) {
  copyFileSync(resolve(srcDir, f), resolve(distDir, f));
  console.log(`Copied ${basename(f)}`);
}

// ─── Extension icons ───────────────────────────────────────────────────────
// The manifest references icons/icon{16,32,48,128}.png for the toolbar action
// and the Chrome Web Store tile. They're rendered source assets committed under
// src/icons/ — copy every PNG there into extension/icons/ so the build is a
// loadable, store-submittable package.
{
  const srcIconsDir = resolve(srcDir, 'icons');
  if (existsSync(srcIconsDir)) {
    const distIconsDir = resolve(distDir, 'icons');
    mkdirSync(distIconsDir, {recursive: true});
    const pngs = readdirSync(srcIconsDir).filter((f) => f.endsWith('.png'));
    for (const png of pngs) {
      copyFileSync(resolve(srcIconsDir, png), resolve(distIconsDir, png));
    }
    console.log(`Copied ${pngs.length} icon${pngs.length === 1 ? '' : 's'} to extension/icons/`);
  } else {
    console.warn('No src/icons/ directory — extension will ship without icons.');
  }
}

// Remove any stale content-script that lingered from the old build.
const stale = resolve(distDir, 'selector-capture-mode.js');
if (existsSync(stale)) { rmSync(stale); console.log(`Removed ${stale}`); }

// README install instructions. The extension is loaded from a Windows browser,
// so when building under WSL the "Load unpacked" path must be the \\wsl.localhost
// UNC path, not the Linux distDir. Off WSL (native Win/macOS/Linux) distDir is
// already the right path for that host.
const loadPath = process.env.WSL_DISTRO_NAME
  ? `\\\\wsl.localhost\\${process.env.WSL_DISTRO_NAME}${distDir.replace(/\//g, '\\')}`
  : distDir;
const installHints = [
  'PinchGrab extension',
  '',
  '1. Open this folder in your file manager.',
  '2. Open edge://extensions or chrome://extensions.',
  '3. Enable Developer mode.',
  '4. Click "Load unpacked" and select:',
  `   ${loadPath}`,
  '5. Pin PinchGrab in the toolbar; click its icon to open the side panel.',
  '6. Open any web page, hold Alt to live-outline elements, Alt+Click to capture.',
  '',
  'Repo: https://github.com/wranngle/pinchgrab',
].join('\n');
writeFileSync(resolve(distDir, 'README.txt'), installHints + '\n');
console.log(`Wrote README.txt`);

// Validate manifest is well-formed JSON.
try {
  JSON.parse(readFileSync(resolve(distDir, 'manifest.json'), 'utf-8'));
} catch (err) {
  console.error('manifest.json is not valid JSON:', err);
  process.exit(1);
}
