// Bundle src/*.ts → extension/*.js using Bun, then copy static assets.
// Each entry (content-script, sidepanel, background, lucide) becomes a
// single self-contained .js file — content scripts don't load ES modules,
// so bundling is mandatory.

import {mkdirSync, copyFileSync, writeFileSync, readFileSync, existsSync, rmSync, readdirSync} from 'node:fs';
import {resolve, basename} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = resolve(fileURLToPath(import.meta.url), '..', '..');
const srcDir = resolve(root, 'src');
const distDir = resolve(root, 'extension');

mkdirSync(distDir, {recursive: true});

// ─── Copy DESIGN.md / SKILL.md templates as extension resources ────────────
// Earlier versions baked these into the sidepanel.js IIFE as string
// constants — that pushed the bundle to ~1.95MB because the files are
// 184KB + 178KB respectively. Better architecture: ship them as separate
// .md files inside the extension and load on demand. The sidepanel
// fetches them via `chrome.runtime.getURL('templates/...')` only when
// the user actually opens the editor modal or exports an archive.
//
// Per-user override: if `src/templates/local.DESIGN.md` exists, its
// content gets copied as `extension/templates/local.DESIGN.md`. The
// sidepanel prefers `local.*` over the generic template on first
// install so a developer can fork the extension and ship a build
// pre-loaded with their actual design source-of-truth. Gitignored.
//
// Only a small `templates.gen.ts` module is emitted — just lists which
// resources are present (so the sidepanel knows which file to fetch
// without a probe round-trip).
{
  const srcTemplatesDir = resolve(srcDir, 'templates');
  const distTemplatesDir = resolve(distDir, 'templates');
  mkdirSync(distTemplatesDir, {recursive: true});
  type TplCopy = {srcName: string; distName: string; required: boolean; key: 'designTemplate' | 'skillTemplate' | 'localDesign' | 'localSkill'};
  const copies: TplCopy[] = [
    {srcName: 'DESIGN.template.md', distName: 'DESIGN.template.md', required: true, key: 'designTemplate'},
    {srcName: 'PinchGrab.SKILL.template.md', distName: 'PinchGrab.SKILL.template.md', required: true, key: 'skillTemplate'},
    {srcName: 'local.DESIGN.md', distName: 'local.DESIGN.md', required: false, key: 'localDesign'},
    {srcName: 'local.SKILL.md', distName: 'local.SKILL.md', required: false, key: 'localSkill'},
  ];
  const present: Record<TplCopy['key'], boolean> = {designTemplate: false, skillTemplate: false, localDesign: false, localSkill: false};
  for (const c of copies) {
    const src = resolve(srcTemplatesDir, c.srcName);
    if (!existsSync(src)) {
      if (c.required) {
        console.error(`Required template missing: ${src}`);
        process.exit(1);
      }
      continue;
    }
    copyFileSync(src, resolve(distTemplatesDir, c.distName));
    present[c.key] = true;
  }
  const gen = `// Auto-generated by scripts/build-extension.ts — do not edit.
// Tells the sidepanel which template resources exist in this build.
// Actual content lives as .md files under extension/templates/, loaded
// lazily via chrome.runtime.getURL — see loadTemplate() in sidepanel.ts.
export const TEMPLATES_PRESENT = ${JSON.stringify(present)} as const;
`;
  writeFileSync(resolve(srcDir, 'templates.gen.ts'), gen);
  console.log(`Templates copied to extension/templates/ (local DESIGN: ${present.localDesign ? 'yes' : 'no'}, local SKILL: ${present.localSkill ? 'yes' : 'no'})`);
}

// ─── Bundled third-party skills ─────────────────────────────────────────────
// third_party/{impeccable,perception-first-design}/ is vendored at pinned
// SHAs by scripts/sync-bundled-skills.ts (UPSTREAM.lock = provenance). The
// build copies the content files into extension/skills/ (gitignored, like
// templates.gen.ts), emits src/bundled-skills.gen.ts so the sidepanel knows
// what to fetch at export time, and generates skills-index.json — the
// machine-readable locator index consuming agents use for mapped_skills.
{
  type LockFileRow = {path: string; sha256: string; bytes: number; purpose?: string};
  type Lock = {repo: string; ref: string; sha: string; license: string; trademark?: string; include: string[]; files: LockFileRow[]};
  type GenRow = {ext: string; archive: string; bytes: number};
  type IndexSkill = {id: string; path: string; purpose: string; source: string; invoke?: string};
  const thirdPartyDir = resolve(root, 'third_party');
  const distSkillsDir = resolve(distDir, 'skills');
  const genRows: GenRow[] = [];
  const indexSources: any[] = [];
  const indexSkills: IndexSkill[] = [];
  // Archive layout per source: impeccable lands under the receiver's
  // .agents tree (it's a skills reference set); perception-first-design
  // ships as its intact repo tree because the pfd skill references its own
  // corpus/framework/commands by relative path.
  const ARCHIVE_ROOT: Record<string, string> = {
    impeccable: '.agents/skills/impeccable',
    'perception-first-design': 'perception-first-design',
  };
  const sourceNames = existsSync(thirdPartyDir)
    ? readdirSync(thirdPartyDir).filter((n) => existsSync(resolve(thirdPartyDir, n, 'UPSTREAM.lock')))
    : [];
  for (const name of sourceNames.sort()) {
    const lock: Lock = JSON.parse(readFileSync(resolve(thirdPartyDir, name, 'UPSTREAM.lock'), 'utf-8'));
    const archiveRoot = ARCHIVE_ROOT[name] ?? name;
    indexSources.push({
      name,
      repo: lock.repo,
      ref: lock.ref,
      sha: lock.sha,
      license: lock.license,
      ...(lock.trademark ? {trademark: lock.trademark} : {}),
      ...(lock.include.some((i) => i !== '(whole tree)') ? {subset: lock.include} : {}),
    });
    for (const row of lock.files) {
      const src = resolve(thirdPartyDir, name, row.path);
      if (!existsSync(src)) {
        console.error(`UPSTREAM.lock lists a missing file: third_party/${name}/${row.path} — re-run bun run sync:skills`);
        process.exit(1);
      }
      const ext = `skills/${name}/${row.path}`;
      const dest = resolve(distSkillsDir, name, row.path);
      mkdirSync(resolve(dest, '..'), {recursive: true});
      copyFileSync(src, dest);
      genRows.push({ext, archive: `${archiveRoot}/${row.path}`, bytes: row.bytes});
    }
    if (name === 'impeccable') {
      for (const row of lock.files) {
        if (!row.path.startsWith('reference/') || !row.path.endsWith('.md')) continue;
        const slug = basename(row.path, '.md');
        indexSkills.push({id: `impeccable/${slug}`, path: `${archiveRoot}/${row.path}`, purpose: row.purpose ?? '', source: name});
      }
    }
    if (name === 'perception-first-design') {
      const skill = lock.files.find((f) => f.path === 'skills/pfd/SKILL.md');
      indexSkills.push({
        id: 'pfd',
        path: `${archiveRoot}/skills/pfd/SKILL.md`,
        purpose: skill?.purpose ?? 'Perception-First Design framework: solve, evaluate, analyze',
        source: name,
        invoke: '/perception-first-design:all',
      });
    }
  }
  if (sourceNames.length) {
    // The PinchGrab triage skill itself is prefs-resolved at export time,
    // but its archive path is stable — index it so mapped_skills can cite it.
    indexSkills.unshift({
      id: 'pinchgrab',
      path: '.agents/skills/PinchGrab/SKILL.md',
      purpose: 'How to read a PinchGrab export and triage its captures (bundled per-export; customized or template).',
      source: 'pinchgrab',
    });
    const index = {kind: 'pinchgrab/skills-index', version: 1, sources: indexSources, skills: indexSkills};
    const indexJson = JSON.stringify(index, null, 2) + '\n';
    mkdirSync(distSkillsDir, {recursive: true});
    writeFileSync(resolve(distSkillsDir, 'skills-index.json'), indexJson);
    genRows.push({ext: 'skills/skills-index.json', archive: 'skills-index.json', bytes: new TextEncoder().encode(indexJson).length});
  }
  const gen = `// Auto-generated by scripts/build-extension.ts — do not edit.
// Inventory of vendored skill resources under extension/skills/ (source of
// truth: third_party/*/UPSTREAM.lock via scripts/sync-bundled-skills.ts).
// \`ext\` is the extension-relative fetch path; \`archive\` is where the file
// lands inside an exported .tar.zst bundle.
export const BUNDLED_SKILLS_PRESENT = ${JSON.stringify(sourceNames.length > 0)};
export type BundledSkillFile = {ext: string; archive: string; bytes: number};
export const BUNDLED_SKILL_FILES: BundledSkillFile[] = ${JSON.stringify(genRows, null, 2)};
`;
  writeFileSync(resolve(srcDir, 'bundled-skills.gen.ts'), gen);
  console.log(`Bundled skills: ${sourceNames.length} sources, ${genRows.length} files → extension/skills/`);
}

// ─── TS entries ───────────────────────────────────────────────────────────
type Entry = {input: string; output: string; minify?: boolean};
const ENTRIES: Entry[] = [
  // lucide.ts is imported by sidepanel.ts and bundled in — no standalone build.
  {input: 'content-script.ts', output: 'content-script.js'},
  {input: 'sidepanel.ts', output: 'sidepanel.js'},
  {input: 'background.ts', output: 'background.js'},
];

const minify = process.env.NODE_ENV === 'production' || process.argv.includes('--minify');

for (const entry of ENTRIES) {
  const result = await Bun.build({
    entrypoints: [resolve(srcDir, entry.input)],
    target: 'browser',
    format: 'iife',
    minify,
    sourcemap: minify ? 'none' : 'inline',
  });
  if (!result.success) {
    console.error(`Build failed for ${entry.input}:`);
    for (const log of result.logs) console.error(log);
    process.exit(1);
  }
  const out = await result.outputs[0]!.text();
  const dest = resolve(distDir, entry.output);
  writeFileSync(dest, out);
  const sizeKb = (out.length / 1024).toFixed(1);
  console.log(`Wrote ${dest} (${sizeKb} KB${minify ? ', minified' : ''})`);
}

// ─── Static assets ────────────────────────────────────────────────────────
const PASSTHROUGH = ['manifest.json', 'sidepanel.html', 'sidepanel.css'];
for (const f of PASSTHROUGH) {
  copyFileSync(resolve(srcDir, f), resolve(distDir, f));
  console.log(`Copied ${basename(f)}`);
}

// ─── Extension icons ───────────────────────────────────────────────────────
// The manifest references icons/icon{16,32,48,128}.png for the toolbar action
// and the Chrome Web Store tile. They're rendered source assets committed under
// src/icons/ — copy every PNG there into extension/icons/ so the build is a
// loadable, store-submittable package.
{
  const srcIconsDir = resolve(srcDir, 'icons');
  if (existsSync(srcIconsDir)) {
    const distIconsDir = resolve(distDir, 'icons');
    mkdirSync(distIconsDir, {recursive: true});
    const pngs = readdirSync(srcIconsDir).filter((f) => f.endsWith('.png'));
    for (const png of pngs) {
      copyFileSync(resolve(srcIconsDir, png), resolve(distIconsDir, png));
    }
    console.log(`Copied ${pngs.length} icon${pngs.length === 1 ? '' : 's'} to extension/icons/`);
  } else {
    console.warn('No src/icons/ directory — extension will ship without icons.');
  }
}

// Remove any stale content-script that lingered from the old build.
const stale = resolve(distDir, 'selector-capture-mode.js');
if (existsSync(stale)) { rmSync(stale); console.log(`Removed ${stale}`); }

// README install instructions. The extension is loaded from a Windows browser,
// so when building under WSL the "Load unpacked" path must be the \\wsl.localhost
// UNC path, not the Linux distDir. Off WSL (native Win/macOS/Linux) distDir is
// already the right path for that host.
const loadPath = process.env.WSL_DISTRO_NAME
  ? `\\\\wsl.localhost\\${process.env.WSL_DISTRO_NAME}${distDir.replace(/\//g, '\\')}`
  : distDir;
const installHints = [
  'PinchGrab extension',
  '',
  '1. Open this folder in your file manager.',
  '2. Open edge://extensions or chrome://extensions.',
  '3. Enable Developer mode.',
  '4. Click "Load unpacked" and select:',
  `   ${loadPath}`,
  '5. Pin PinchGrab in the toolbar; click its icon to open the side panel.',
  '6. Open any web page, hold Alt to live-outline elements, Alt+Click to capture.',
  '',
  'Repo: https://github.com/wranngle/pinchgrab',
].join('\n');
writeFileSync(resolve(distDir, 'README.txt'), installHints + '\n');
console.log(`Wrote README.txt`);

// Validate manifest is well-formed JSON.
try {
  JSON.parse(readFileSync(resolve(distDir, 'manifest.json'), 'utf-8'));
} catch (err) {
  console.error('manifest.json is not valid JSON:', err);
  process.exit(1);
}
